# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf186905edf3f104c74d3bfc55a1db65ae96148bc09425adc0c5e2c52b0bf262da8da288faa5c18117c57f046328bf4ec7c938282810f3f5607272e1e511f473

test:
  secret_key_base: 96799e0ac33cf22e7ac049774ed4b89439a8926e1fd33f722298e474ff70eaf0ee58abff6e7ba5397485c2fe824c80f00e6e28095716a9bbb3e1ef62196cb842

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
